
# To install packages
- name: install packages through loops
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    
    loop:
    - nginx
    - zip
    - mysql


# To install and Uninstall packages

- name: Install and remove packages
  hosts: frontend
  become: yes
  tasks:
  - name: install and remove packages through loops
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state}}"
    
    loop:
    - {name: 'nginx', state: 'absent'}
    - {name: 'zip', state: 'absent'}
    - {name: 'nodejs', state: 'present'}


# To install and Uninstall packages through command line

- name: Install and remove packages
  hosts: frontend
  become: yes
  tasks:
    - name: Install and remove packages using a loop
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ packages }}"

# Command line

#  ansible-playbook -i inventory.ini 18-loop-packages.yaml -e 'packages=[{"name":"nginx","state":"absent"},{"name":"zip","state":"absent"},{"name":"nodejs","state":"present"}]'
