- name: shell vs command
  hosts: frontend
  become: yes
  tasks:
  - name: to get output of ls using shell 
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt" # for command it will not work because of redirection >
    register: output_value

  - name: print output value
    ansible.builtin.debug:
      msg: "{{ output_value }}"

  - name: to get output of ls using command
    ansible.builtin.command: "ls -ltr" # this willwork, becasue we are not using any special things like (redirections, pipe)
    register: output_commandvalue

  - name: print output output_commandvalue
    ansible.builtin.debug:
      msg: "{{ output_commandvalue }}"
      