- name: create ec2 and route 53 records
  hosts: local
  connection: local
  vars:
    instances:
    - frontend
    - mysql
    - backend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: subnet-04221224700909e98
      instance_type: t3.micro
      security_group: sg-07b3efc937a5811da
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
      loop: "{{ instances }}"