- name: configure nginx
  hosts: dynamic_Ansible
  become: yes
  tasks:

  - name: install
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes