# - name: play level variables
#   hosts: local
#   connection: local
#   vars:
#     NAME: Viswesh
#     Age: 26
#   tasks:

#   - name: print viswesh info
#     ansible.builtin.debug:
#       msg: "I am {{ NAME }} , with {{ Age }}"

#--------------------------------------------------------

# - name: task level variables
#   hosts: local
#   connection: local
#   tasks:

#   - name: print task level viswesh info
#     vars:
#       NAME: viswesh
#       Age: 26
#     ansible.builtin.debug:
#        msg: "I am {{ NAME }} , with {{ Age }}"

#--------------------------------------------------------


# - name: prefernce b/w play and task level\
#   hosts: local
#   connection: local
#   vars:
#     NAME: Viswesh
#     Age: 24
#   tasks:

#   - name: print info
#     vars:
#       NAME: Suresh
#       Age: 53
#     ansible.builtin.debug:
#       msg: "I am {{ NAME }} , with {{ Age }}"

#   - name: print play info
#     ansible.builtin.debug:
#       msg: "I am {{ NAME }} , with {{ Age }}"

   #--------------------------------------------------------

# - name: print file level variable
#   hosts: local
#   connection: local
#   vars_files:
#   - practiceinfo.yaml
#   tasks:
#   - name: print info
#     ansible.builtin.debug:
#       msg: "I am {{ NAME }} , with {{ Age }}"

#--------------------------------------------------------


# - name: inventory level info
#   hosts: local
#   connection: local
#   tasks:
#   - name: print inventory level info
#     ansible.builtin.debug:
#       msg: "I am {{ NAME }} , with {{ Age }}"

#--------------------------------------------------------

# - name: prompt level variables
#   hosts: local
#   connection: local
#   vars_prompt:
  
#     - name: USERNAME
#       prompt: please enter your username
#       private: true

#     - name: PASSWORD
#       prompt: please enter your password
#       private: true

#   tasks:

#   - name: print user info
#     ansible.builtin.debug:
#       msg: "username is {{ USERNAME }} and Password is {{ PASSWORD }}"

  #--------------------------------------------------------

# - name: command line info
#   hosts: local
#   connection: local
#   tasks:

#   - name: print info command
#     ansible.builtin.debug:
#       msg: "username is {{ USERNAME }} and Password is {{ PASSWORD }}"


#--------------------------------------------------------

# - name: check when condition
#   hosts: local
#   connection: local
#   vars:
#     NUMBER: 500

#   tasks:
  
#   - name: print number less than 50
#     ansible.builtin.debug:
#       msg: "the given number is {{ NUMBER }} less than 100"
#     when: NUMBER < 100

#   - name: print number greater than 100
#     ansible.builtin.debug:
#       msg: "the given number is {{ NUMBER }} greater than 100"
#     when: NUMBER > 100

#--------------------------------------------------------

# - name: gathering facts
#   hosts: local
#   connection: local
#   tasks:
#   - name: print gathering facts
#     ansible.builtin.debug:
#       msg: "{{ ansible_facts }}"

#--------------------------------------------------------

# - name: playbook control using facts
#   hosts: frontend
#   become: yes
#   tasks:

#   - name: install when os-family is Redhat
#     ansible.builtin.dnf:
#       name: nginx
#       state: present
#     when: ansible_os_family == "RedHat"

#   - name: instll when os-family is Debian
#     ansible.builtin.apt:
#       name: nginx
#       state: present
#     when: ansible_os_family == "Debian"


#--------------------------------------------------------

# - name: loops
#   hosts: local
#   connection: local
#   tasks:

#   - name: print loop values
#     ansible.builtin.debug:
#       msg: "print names: {{ item }}"
#     loop:
#     - Suresh
#     - viswesh
#     - varsha

#--------------------------------------------------------

# - name: install packages
#   hosts: frontend
#   become: yes
#   tasks:

#   - name: install packages using loops
#     ansible.builtin.dnf:
#       name: "{{ item }}"
#       state: present
#     loop:

#     - nginx
#     - zip
#     - mysql

#--------------------------------------------------------

# - name: install and uninstall packages using loops
#   hosts: frontend
#   become: yes
#   tasks:

#   - name: install and uninstall
#     ansible.builtin.dnf:
#       name: "{{ item.name }}"
#       state: "{{ item. state }}"
    
#     loop:

#     - {"name": "nginx" , "state": "absent" }
#     - {"name": "zip" , "state": "present"}
#     - {"name": "mysql", "state": "absent"}

#-----------------------------------------------------------

# - name: check default function
#   hosts: local
#   connection: local
#   tasks:
  
#   - name: print default value
#     ansible.builtin.debug:
#       msg: "{{ person | default('vishu')}}"

#-----------------------------------------------------------

- name: string to list
  hosts: local
  connection: local
  vars:
    CRICKETERS: "rohit,virat,bumrah"
  tasks:

  - name: print string to list
    ansible.builtin.debug:
      msg: " Cricketers are {{ CRICKETERS | split(',') }}"